# render.yaml
services:
  - type: web
    name: khayriddinov-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    autoDeploy: true
